### ISSUE TITLE
Please add release build times

### ISSUE THREAD

**Issue by lnicola** [rust-cli/argparse-benchmarks-rs#19]
They can still matter, for CI release builds, or even locally.

**Comment by epage** [comment]
Are there cases where inferring the release build time behavior from debug builds is misleading?  I'm assuming debug builds are representative enough for someone making a decision on which crate has acceptable performance.

**Comment by lnicola** [comment]
It's not always important, but it can matter: if a crate slows CI release builds by 10x, that can be a good reason to avoid it.

Can the release build times be inferred from the debug ones? No idea, maybe. I certainly couldn't. But I implemented it, so even if you don't want to add them, people who are interested can find this comment:

Name | Overhead (release) | Build (debug) | Build (release) | Parse (release) | Invalid UTF-8 | Downloads | Version
-----|--------------------|----------------|---------------|-----------------|---------------|-----------|--------
null | 0 KiB | 408ms | 419ms | 1ms | Y | ![Download count](https://img.shields.io/crates/dr/None) | -
argh | 54 KiB | 3.09s | 2.85s | 1ms | N | ![Download count](https://img.shields.io/crates/dr/argh) | v0.1.7
clap | 959 KiB | 2.88s | 3.48s | 2ms | Y | ![Download count](https://img.shields.io/crates/dr/clap) | v3.0.0
clap-minimal | 895 KiB | 2.81s | 3.24s | 1ms | Y | ![Download count](https://img.shields.io/crates/dr/clap) | v3.0.0
clap_derive | 966 KiB | 5.97s | 6.15s | 2ms | Y | ![Download count](https://img.shields.io/crates/dr/clap) | v3.0.0
gumdrop | 53 KiB | 3.06s | 2.85s | 1ms | N | ![Download count](https://img.shields.io/crates/dr/gumdrop) | v0.8.0
lexopt | 55 KiB | 559ms | 693ms | 2ms | Y | ![Download count](https://img.shields.io/crates/dr/lexopt) | v0.2.0
pico-args | 40 KiB | 569ms | 605ms | 1ms | Y | ![Download count](https://img.shields.io/crates/dr/pico-args) | v0.4.2
xflags | 33 KiB | 931ms | 931ms | 1ms | Y | ![Download count](https://img.shields.io/crates/dr/xflags) | v0.2.3

*System: Linux 5.15.12-arch1-1 (x86_64) w/ `-j 32`*

PS: my overhead numbers are different from yours, no idea why.

**Comment by epage** [comment]
Interesting to see the `-j2` numbers.  A bit what I'd expect.
