### ISSUE TITLE
Consider release build with lto=fat or codegen-units=1

### ISSUE THREAD

**Issue by e00E** [rust-cli/argparse-benchmarks-rs#33]
https://doc.rust-lang.org/cargo/reference/profiles.html#lto
https://github.com/johnthagen/min-sized-rust

Unsure how useful this is because most people probably use the default release profile but it could be interesting to see how binary size changes with a slower but more optimized build. `strip = true` could also be included.

**Comment by epage** [comment]
I think I'd rather leave things as default rather than optimize for one case or the other.
