### ISSUE TITLE
What does "recent downloads: 12" mean for "null" parser? 

### ISSUE THREAD

**Issue by vi** [rust-cli/argparse-benchmarks-rs#37]
I assumed that "null" parser in "Results" table means absence of any parser crate. If so, then what does the nonzero download counter mean? It looks a bit like a hypothetical download counter for [VanillaJS](http://vanilla-js.com/) framework.

And number of times users _didn't_ download any crate is much higher than 12.

**Comment by epage** [comment]
It was naive code putting the link in even if there wasn't actually a crate for it, so it just links to whatever the "null" crate is.  It is now fixed to not have a link.
