### ISSUE TITLE
Document -j used

### ISSUE THREAD

**Issue by matklad** [rust-cli/argparse-benchmarks-rs#6]
The time results differ significantly based on the amount of cores. It’d be good to document the number of cores used, or split cpu and wallclock times.

**Comment by epage** [comment]
Yes, I want to capture that along with system specs. I just haven't taken the time to collect that information in python yet

(I also consider it a bug in the Rust ecosystem that I reached for Python :) )

**Comment by epage** [comment]
btw you can look at the [raw run results](https://github.com/rust-cli/argparse-benchmarks-rs/blob/main/runs/2021-07-21-epage-sc01.json) which includes user/system which gives a sense of things.
